id: D94BB00E4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:04:59+00:00'
last_modified: '2022-05-29T08:57:07.266758+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    45c0:
      image_group_id: I1PD95933
      title: ལས་བརྒྱ་རྩ་གཅིག་པ།
      total_pages: 1560
      order: 88
      base_file: 45c0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
